name: CI

on: [push, pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Run lint
              uses: jidicula/clang-format-action@v4.11.0
              with:
                  clang-format-version: "13"
                  fallback-style: "LLVM"

    build-linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y g++ make
            - name: Build
              run: make
              env:
                  CC: gcc
                  CXX: g++

    build-macos:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build
              run: make
              env:
                  CC: gcc
                  CXX: g++
